// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebAPI;

#nullable disable

namespace WebAPI.Migrations
{
	[DbContext(typeof(FlightsDbContext))]
	partial class FlightsDbContextModelSnapshot : ModelSnapshot
	{
		protected override void BuildModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "7.0.10")
				.HasAnnotation("Relational:MaxIdentifierLength", 63);

			NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

			modelBuilder.Entity("WebAPI.Flight", b =>
				{
					b.Property<int>("ID")
						.ValueGeneratedOnAdd()
						.HasColumnType("integer");

					NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

					b.Property<string>("Airline")
						.IsRequired()
						.HasColumnType("text");

					b.Property<string>("ArrivalCity")
						.IsRequired()
						.HasColumnType("text");

					b.Property<DateTime>("ArrivalDatetime")
						.HasColumnType("timestamp with time zone");

					b.Property<string>("DepartureCity")
						.IsRequired()
						.HasColumnType("text");

					b.Property<DateTime>("DepartureDatetime")
						.HasColumnType("timestamp with time zone");

					b.Property<double>("Price")
						.HasColumnType("double precision");

					b.HasKey("ID");

					b.ToTable("Flights");
				});
#pragma warning restore 612, 618
		}
	}
}
